-- 공통 Flyway가 유일한 Schema owner다. 원본 JSON과 서비스용 파생 값을 함께 보존한다.
CREATE TABLE support_program_sync_history (
    run_id VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
    sync_scope VARCHAR(10) NOT NULL,
    profile VARCHAR(10) NOT NULL,
    status VARCHAR(10) NOT NULL,
    started_at DATETIME(6) NOT NULL,
    finished_at DATETIME(6) NULL,
    report_json JSON NULL,
    CHECK (sync_scope IN ('SAMPLE', 'PARTIAL', 'FULL')),
    CHECK (profile = 'dev'),
    CHECK (status IN ('RUNNING', 'SUCCESS', 'FAILED'))
) ENGINE=InnoDB;

CREATE TABLE support_programs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    pblanc_id VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
    name LONGTEXT NULL,
    announcement_url LONGTEXT NULL,
    jurisdiction_name LONGTEXT NULL,
    executing_org_name LONGTEXT NULL,
    summary_html LONGTEXT NULL,
    category LONGTEXT NULL,
    source_created_raw LONGTEXT NULL,
    application_period_raw LONGTEXT NULL,
    source_updated_raw LONGTEXT NULL,
    target LONGTEXT NULL,
    inquiry_count BIGINT NULL,
    attachment_urls_raw LONGTEXT NULL,
    attachment_names_raw LONGTEXT NULL,
    primary_url_raw LONGTEXT NULL,
    primary_filename_raw LONGTEXT NULL,
    hashtags_raw LONGTEXT NULL,
    application_method_raw LONGTEXT NULL,
    contact_raw LONGTEXT NULL,
    application_url_raw LONGTEXT NULL,
    source_payload JSON NOT NULL,
    source_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    fingerprint_version SMALLINT NOT NULL DEFAULT 1,
    source_created_at DATETIME NULL,
    source_updated_at DATETIME NULL,
    application_start_date DATE NULL,
    application_end_date DATE NULL,
    last_seen_at DATETIME(6) NOT NULL,
    last_seen_run_id VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_active BOOLEAN NOT NULL,
    source_deleted BOOLEAN NOT NULL,
    source_deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    FOREIGN KEY (last_seen_run_id) REFERENCES support_program_sync_history(run_id),
    INDEX idx_source_presence (source_active, last_seen_run_id),
    CHECK ((source_active = 1 AND source_deleted = 0 AND source_deleted_at IS NULL)
        OR (source_active = 0 AND source_deleted = 1 AND source_deleted_at IS NOT NULL)),
    CHECK (application_start_date IS NULL OR application_end_date >= application_start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
