-- 적용된 V1은 보존하고 실제 SHOW CREATE TABLE 정의를 유지한 채 COMMENT만 추가한다.
ALTER TABLE `support_program_sync_history`
    COMMENT = '기업마당 구조화 공고 동기화의 실행 범위·상태·품질 검증 결과를 보존하는 실행 이력. 공고의 마지막 관측 run 관계와 재조정 완전성 판단의 근거다.',
    MODIFY COLUMN `run_id` varchar(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '동기화 실행의 고유 ID. 공고의 last_seen_run_id와 연결하며 동일 실행 ID 재사용을 금지한다.',
    MODIFY COLUMN `sync_scope` varchar(10) NOT NULL COMMENT '실행 범위 SAMPLE/PARTIAL/FULL. 미관측 공고의 삭제 표시는 완전성이 검증된 FULL에서만 허용한다.',
    MODIFY COLUMN `profile` varchar(10) NOT NULL COMMENT '동기화 실행 환경 Profile. 현재 dev만 허용하며 Git 브랜치 이름과는 별개다.',
    MODIFY COLUMN `status` varchar(10) NOT NULL COMMENT 'DB 실행 상태 RUNNING/SUCCESS/FAILED. 품질 report_json의 PASS/FAIL 판정과 구분한다.',
    MODIFY COLUMN `started_at` datetime(6) NOT NULL COMMENT 'DB 동기화 실행 이력 기록을 시작한 UTC 시각. 마이크로초 정밀도의 시간대 없는 DATETIME에 UTC를 저장한다.',
    MODIFY COLUMN `finished_at` datetime(6) DEFAULT NULL COMMENT 'DB 동기화 실행 결과를 기록한 UTC 시각. 실행 중에는 NULL이며 마이크로초 정밀도로 저장한다.',
    MODIFY COLUMN `report_json` json DEFAULT NULL COMMENT '실행 건수·품질 지표·완전성 검증·재조정 실행 또는 제외 사유를 담은 기계 판독 JSON. 인증정보와 원문 예외 메시지를 저장하지 않는다.';

ALTER TABLE `support_programs`
    COMMENT = '기업마당 지원사업 공고의 API 원본과 서비스용 정형·파생값 및 원본 존재 상태를 저장하는 구조화 공고의 사실 저장소. 검색·원본 변경 감지·관측 이력 연결에 사용한다.',
    MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'MySQL 내부 공고 행 식별자. 자동 증가하며 외부 연계 비즈니스 키인 pblanc_id와 구분한다.',
    MODIFY COLUMN `pblanc_id` varchar(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '기업마당 pblancId 원본 공고 ID이자 중복 불가 비즈니스 키. 공고·문서·향후 검색 데이터를 연결하며 ASCII 대소문자를 구분한다.',
    MODIFY COLUMN `name` longtext COMMENT '기업마당 pblancNm 공고명 원본 문자열. 공백과 원본 표기를 변형하지 않는다.',
    MODIFY COLUMN `announcement_url` longtext COMMENT '기업마당 pblancUrl 상세 공고 페이지 URL 원문. 파일 다운로드 URL이나 접수 홈페이지 URL과 구분한다.',
    MODIFY COLUMN `jurisdiction_name` longtext COMMENT '기업마당 jrsdInsttNm 소관기관명 원문. 사업 수행기관 executing_org_name과 구분한다.',
    MODIFY COLUMN `executing_org_name` longtext COMMENT '기업마당 excInsttNm 사업 수행기관명 원문. 소관기관 jurisdiction_name과 구분한다.',
    MODIFY COLUMN `summary_html` longtext COMMENT '기업마당 bsnsSumryCn 사업개요 원문. HTML markup을 제거하거나 요약하지 않고 보존한다.',
    MODIFY COLUMN `category` longtext COMMENT '기업마당 pldirSportRealmLclasCodeNm 지원 분야명 원문. 별도 분류 코드나 추론한 업종으로 변환하지 않는다.',
    MODIFY COLUMN `source_created_raw` longtext COMMENT '기업마당 creatPnttm 등록 시각 원본 문자열. 파싱된 source_created_at과 별도로 시간대 미확정 원문을 보존한다.',
    MODIFY COLUMN `application_period_raw` longtext COMMENT '기업마당 reqstBeginEndDe 신청기간 원본 문자열. 날짜 범위뿐 아니라 예산 소진시까지 등 FREE_TEXT도 변형 없이 보존한다.',
    MODIFY COLUMN `source_updated_raw` longtext COMMENT '기업마당 updtPnttm 수정 시각 원본 문자열. DB content 수정 시각 updated_at과 구분한다.',
    MODIFY COLUMN `target` longtext COMMENT '기업마당 trgetNm 지원대상 명칭 원문. 실제 신청 자격 충족 여부를 판정한 값이 아니다.',
    MODIFY COLUMN `inquiry_count` bigint DEFAULT NULL COMMENT '기업마당 inqireCo 조회 횟수 원본 정수. 단위는 회이며 소스의 조회 수이지 서비스 자체 조회 통계가 아니다.',
    MODIFY COLUMN `attachment_urls_raw` longtext COMMENT '기업마당 flpthNm 부가 첨부 후보 URL 원문. NULL 및 @ 연결 문자열을 보존하며 filename과의 의미상 순서 대응은 미확정이다.',
    MODIFY COLUMN `attachment_names_raw` longtext COMMENT '기업마당 fileNm 부가 첨부 후보 파일명 원문. NULL 및 @ 연결 문자열을 보존하며 attachment_urls_raw와의 의미상 pairing은 미확정이다.',
    MODIFY COLUMN `primary_url_raw` longtext COMMENT '기업마당 printFlpthNm 주 공고문 후보 다운로드 URL 원문. 다운로드 검증을 통과했더라도 실제 본공고 역할은 본문 의미 검증 전 미확정이다.',
    MODIFY COLUMN `primary_filename_raw` longtext COMMENT '기업마당 printFileNm 주 공고문 후보 파일명 원문. 파일 확장자는 metadata이며 실제 파일 signature나 내용 판정을 대체하지 않는다.',
    MODIFY COLUMN `hashtags_raw` longtext COMMENT '기업마당 hashtags 해시태그 원본 문자열. 분리·재분류하지 않고 원본 순서와 표기를 보존한다.',
    MODIFY COLUMN `application_method_raw` longtext COMMENT '기업마당 reqstMthPapersCn 신청 방법 원문. 개행·접수 안내를 정규화하거나 별도 절차로 추론하지 않는다.',
    MODIFY COLUMN `contact_raw` longtext COMMENT '기업마당 refrncNm 문의처 원문. 기관 안내와 연락 정보를 원본대로 보존하며 별도 담당자 추론은 하지 않는다.',
    MODIFY COLUMN `application_url_raw` longtext COMMENT '기업마당 rceptEngnHmpgUrl 접수 홈페이지 URL 원문. NULL을 허용하며 상세 공고 페이지나 공고문 다운로드 URL과 구분한다.',
    MODIFY COLUMN `source_payload` json NOT NULL COMMENT '기업마당 API item 원본 JSON. key 누락/null/빈 문자열/unknown field 구분을 보존하는 소스 내용 기준이다.',
    MODIFY COLUMN `source_fingerprint` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'source_payload를 결정론적 canonical JSON으로 직렬화한 SHA-256 변경 감지 fingerprint. DB 관측 시각·run·존재 상태는 입력에 포함하지 않는다.',
    MODIFY COLUMN `fingerprint_version` smallint NOT NULL DEFAULT '1' COMMENT 'source fingerprint 직렬화 정책 버전. 현재 1이며 source content hash의 해석 기준을 나타낸다.',
    MODIFY COLUMN `source_created_at` datetime DEFAULT NULL COMMENT 'creatPnttm 원문을 안전하게 파싱한 소스 등록 시각 파생값. 파싱 불가 시 NULL이며 소스 시간대는 추측하지 않는다.',
    MODIFY COLUMN `source_updated_at` datetime DEFAULT NULL COMMENT 'updtPnttm 원문을 안전하게 파싱한 소스 수정 시각 파생값. 파싱 불가 시 NULL이며 UTC lifecycle 시각과 구분한다.',
    MODIFY COLUMN `application_start_date` date DEFAULT NULL COMMENT 'application_period_raw가 유효한 DATE_RANGE이고 시작일이 종료일 이하일 때만 생성한 신청 시작일. FREE_TEXT는 NULL이다.',
    MODIFY COLUMN `application_end_date` date DEFAULT NULL COMMENT 'application_period_raw의 안전한 DATE_RANGE에서 생성한 신청 종료일. FREE_TEXT 또는 유효하지 않은 범위는 NULL이다.',
    MODIFY COLUMN `last_seen_at` datetime(6) NOT NULL COMMENT '소스 공고를 정상 관측 처리한 마지막 UTC 시각. SAMPLE/PARTIAL 및 동일 원문 재실행에서도 갱신하며 마이크로초 정밀도로 저장한다.',
    MODIFY COLUMN `last_seen_run_id` varchar(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '해당 공고를 마지막으로 정상 관측 처리한 동기화 실행 ID. support_program_sync_history.run_id를 참조한다.',
    MODIFY COLUMN `source_active` tinyint(1) NOT NULL COMMENT 'true는 정상 소스 관측 상태로 SAMPLE/PARTIAL 복원도 포함한다. false는 검증된 FULL 미관측 상태이며 실제 접수 가능 여부와 무관하다.',
    MODIFY COLUMN `source_deleted` tinyint(1) NOT NULL COMMENT 'true는 완전성이 검증된 FULL에서 소스 미관측으로 삭제 표시된 상태, false는 정상 관측 상태다. 물리 삭제 여부가 아니다.',
    MODIFY COLUMN `source_deleted_at` datetime(6) DEFAULT NULL COMMENT 'source_deleted가 true로 전환된 UTC 시각. 마이크로초 정밀도이며 재관측으로 false가 되면 NULL로 복원한다.',
    MODIFY COLUMN `created_at` datetime(6) NOT NULL COMMENT '공고 행을 MySQL에 최초 INSERT한 UTC 시각. 소스 등록 시각과 구분하며 마이크로초 정밀도로 저장한다.',
    MODIFY COLUMN `updated_at` datetime(6) NOT NULL COMMENT '공고 source content가 INSERT 또는 fingerprint 변경 UPDATE된 UTC 시각. CONTENT_NOOP 관측과 lifecycle만의 변경에는 갱신하지 않는다.';
