CREATE TABLE document_acquisition_runs (
    run_id VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY COMMENT '문서 전체 수집 실행의 고유 ID. 동일 ID 재사용과 결과 덮어쓰기를 금지한다.',
    profile VARCHAR(10) NOT NULL COMMENT '문서 수집 실행 환경 Profile. 현재 dev만 허용하며 Git 브랜치와 구분한다.',
    status VARCHAR(12) NOT NULL COMMENT '실행 진행 상태 RUNNING/COMPLETED/FAILED. 개별 다운로드 성공률과 구분한다.',
    gate_status VARCHAR(10) NOT NULL COMMENT '문서 수집 품질 판정 PENDING/PASS/FAIL. 실패 문서가 하나라도 있으면 PASS가 아니다.',
    source_snapshot_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '대상 공고 ID·source fingerprint·문서 후보 원문을 결정론적으로 직렬화한 SHA-256. 실행 중 Source 변경을 탐지한다.',
    started_at DATETIME(6) NOT NULL COMMENT '문서 수집 실행을 시작한 UTC 시각. 마이크로초 정밀도의 시간대 없는 DATETIME에 UTC를 저장한다.',
    finished_at DATETIME(6) NULL COMMENT '문서 수집 결과를 확정한 UTC 시각. 실행 중에는 NULL이다.',
    report_json JSON NULL COMMENT '후보·다운로드·형식·중복·실패·무결성 지표와 실패 공고를 보존하는 기계 판독 결과. 인증정보는 저장하지 않는다.',
    CHECK (profile = 'dev'),
    CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED')),
    CHECK (gate_status IN ('PENDING', 'PASS', 'FAIL'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
COMMENT='기업마당 공고에 연결된 문서 후보 전체 수집 실행과 품질 결과를 저장한다. Document Source Layer의 실행 감사·재개 판단 근거다.';

CREATE TABLE document_sources (
    candidate_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY COMMENT 'pblanc_id·source field·token index·source URL로 계산한 결정론적 SHA-256 문서 후보 관계 키.',
    pblanc_id VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '문서 후보를 제공한 기업마당 공고 ID. support_programs.pblanc_id와 연결한다.',
    source_role VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '원본 필드 계보 PRINT_CANDIDATE 또는 ATTACHMENT_CANDIDATE. 실제 본공고·부속문서 의미를 확정하지 않는다.',
    source_url_field VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '후보 URL을 발견한 기업마당 API 원본 field명 printFlpthNm 또는 flpthNm.',
    source_filename_field VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '후보 파일명을 발견한 기업마당 API 원본 field명 printFileNm 또는 fileNm.',
    source_token_index INT UNSIGNED NOT NULL COMMENT '@ 연결 원본 문자열에서 후보 URL의 0부터 시작하는 위치. URL과 파일명 관계 검증에 사용한다.',
    source_url LONGTEXT NOT NULL COMMENT '기업마당 API 문서 후보 URL 원문. 인증정보를 추가하거나 정규화하지 않는다.',
    source_url_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'source_url UTF-8 byte의 SHA-256. 긴 URL 중복 조회와 동일 URL 1회 요청에 사용한다.',
    original_filename LONGTEXT NULL COMMENT '동일 token 위치의 printFileNm 또는 fileNm 원본 파일명. pairing 불가 시 NULL을 허용한다.',
    pairing_status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'URL·파일명 token 위치 관계 MATCHED/UNPAIRED. MATCHED도 의미상 동일 문서 보장을 뜻하지 않는다.',
    declared_extension VARCHAR(10) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '원본 파일명에서 관찰한 확장자 PDF/HWP/HWPX/ZIP/XLSX/OTHER/UNKNOWN. 실제 format 판정과 구분한다.',
    download_status VARCHAR(12) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '현재 후보 처리 상태 PENDING/ACQUIRED/FAILED. ACQUIRED는 원본 byte 무결성 확보를 뜻하며 본문 의미 검증은 아니다.',
    failure_category VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '실패 분류 URL_POLICY_ERROR/HTTP_ERROR/TRANSPORT_ERROR/REDIRECT_ERROR/EMPTY_FILE/SIZE_LIMIT_EXCEEDED/INVALID_RESPONSE/SECURITY_REJECTED. 성공 시 NULL이다.',
    http_status SMALLINT UNSIGNED NULL COMMENT '최종 문서 HTTP 응답 status code. 요청 전 정책 실패나 transport 실패는 NULL이다.',
    redirect_count SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '허용 경계 안에서 따라간 HTTP redirect 횟수. 공급자 공식 제한이 아닌 로컬 최대값을 적용한다.',
    content_type VARCHAR(255) NULL COMMENT '최종 HTTP Content-Type의 media type 원문 소문자 값. Binary signature 판정을 대체하지 않는다.',
    detected_format VARCHAR(10) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '실제 byte signature 또는 제한된 container 구조로 식별한 PDF/HWP/HWPX/ZIP/XLSX/OTHER/UNKNOWN.',
    format_mismatch BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'true는 original_filename 확장자와 detected_format이 다름을 뜻한다. 실제 byte format을 filename에 맞춰 변경하지 않는다.',
    invalid_response BOOLEAN NOT NULL DEFAULT FALSE COMMENT 'true는 HTML 오류 page 등 정상 문서로 인정할 수 없는 응답 body임을 뜻한다. 원본 증거는 실패 영역에 보존할 수 있다.',
    byte_size BIGINT UNSIGNED NULL COMMENT '로컬에 보존한 원본 byte 크기. body가 없으면 NULL이며 단위는 byte다.',
    content_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '보존 원본 byte의 SHA-256. 동일 content dedupe와 Parser 입력 무결성 확인에 사용한다.',
    storage_path VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT '저장소 루트 기준 원본 binary 상대 경로. 성공 byte는 content SHA 기반 경로이며 MySQL에 binary를 저장하지 않는다.',
    last_run_id VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '이 후보 관계를 마지막으로 검증·갱신한 document_acquisition_runs.run_id.',
    last_run_action VARCHAR(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '마지막 실행 동작 DOWNLOADED/REUSED_EXISTING/REUSED_URL/FAILED. 실제 HTTP 요청 수 집계와 재실행 판단에 사용한다.',
    last_http_requests SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '마지막 실행에서 이 관계에 귀속한 실제 HTTP 요청 횟수. 동일 URL 관계 중 첫 관계에만 요청 수를 기록한다.',
    first_seen_at DATETIME(6) NOT NULL COMMENT '해당 후보 관계를 DB에서 최초 발견한 UTC 시각.',
    last_seen_at DATETIME(6) NOT NULL COMMENT '현재 구조화 Source에서 해당 후보 관계를 마지막으로 확인한 UTC 시각.',
    last_attempted_at DATETIME(6) NULL COMMENT '해당 후보 URL의 실제 HTTP 요청을 마지막으로 시도한 UTC 시각. 재사용만 한 경우 기존 값을 유지한다.',
    acquired_at DATETIME(6) NULL COMMENT '현재 content byte를 안전하게 확보한 UTC 시각. 실패 상태면 NULL이다.',
    FOREIGN KEY (pblanc_id) REFERENCES support_programs(pblanc_id),
    FOREIGN KEY (last_run_id) REFERENCES document_acquisition_runs(run_id),
    INDEX idx_document_source_url (source_url_sha256),
    INDEX idx_document_content_sha (content_sha256),
    INDEX idx_document_program (pblanc_id, source_role),
    INDEX idx_document_status (download_status, failure_category),
    CHECK (source_role IN ('PRINT_CANDIDATE', 'ATTACHMENT_CANDIDATE')),
    CHECK (source_url_field IN ('printFlpthNm', 'flpthNm')),
    CHECK (source_filename_field IN ('printFileNm', 'fileNm')),
    CHECK (pairing_status IN ('MATCHED', 'UNPAIRED')),
    CHECK (download_status IN ('PENDING', 'ACQUIRED', 'FAILED')),
    CHECK ((download_status = 'ACQUIRED' AND failure_category IS NULL AND byte_size > 0 AND content_sha256 IS NOT NULL AND storage_path IS NOT NULL AND acquired_at IS NOT NULL)
        OR (download_status <> 'ACQUIRED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
COMMENT='기업마당 공고의 문서 후보 URL·원본 field 관계와 다운로드·형식·checksum·로컬 저장 정보를 보존한다. Binary 자체는 저장하지 않는다.';
